feat: ready to review
VlaPol/TMS_Lesson_14 pull request #1
Opened 2023-02-20 16:24 UTC by VlaPol

2023-02-23 18:38 UTC, oleg-grigorijan requested changes

2023-02-23 18:38 UTC, grigo-oleg commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +    private BigDecimal rate;
Если не предполагается изменение полей, то их объявляют final

2023-02-23 18:38 UTC, grigo-oleg commented on src/Homework14Test.java
> +                    Currency outputCurrency = Currency.valueOf(scanner.nextLine());
inputCurrencyCode, outputCurrency –  Используем единообразные название в контексте небольших участков кода.

2023-02-23 18:38 UTC, oleg-grigorijan commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +    public ExchangeRate getExchangeRate(Currency currency){
Это не ответственность класса ExchangeRate. Один объект ExchangeRate знает только о курсе для одной валюты. То есть объект в общем случае владеет данными из своих полей и данными, которые передают в параметры методов. То есть объект ExchangeRate не владеет данными о других курсах валют. Методы объекта в общем случае из статического могут использовать только примитивные константы и простые util-функции (например, какие-то общие операции над String). В статических функциях мы не описываем бизнес-процессы, чтобы пользоваться всеми преимуществами ООП подхода.

2023-02-23 18:38 UTC, oleg-grigorijan commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +    private static BigDecimal currentRates(Currency currency) {
Ответственность аккумулирования множества курсов валют лежит на классе ExchangeService. Как минимум это должно быть туда перенесено. Вообще то что мы тут можем статически в switch задать курсы валют – это допущение задания. Предполагается, что в реальности мы запрашиваем эти данные из внешнего источника. Предполагается, что данные на каждый день будут разными

2023-02-23 18:38 UTC, oleg-grigorijan commented on src/by/tms/lesson14/homework/currency/ExchangeService.java
> +        BigDecimal outputCurRate = new BigDecimal(0);
Можно BigDecimal.ZERO или null, чтобы не выделять память под лишние объекты

2023-02-23 18:38 UTC, oleg-grigorijan commented on src/by/tms/lesson14/homework/currency/ExchangeService.java
> +            return BigDecimal.valueOf(0);
Написал все возможные виды создания нуля для BigDecimal. Для однообразия можешь использовать везде BigDecimal.ZERO

2023-02-23 18:38 UTC, oleg-grigorijan commented on src/by/tms/lesson14/homework/currency/ExchangeService.java
> +            return outputCurRate.compareTo(BigDecimal.ZERO) == 0
Вряд ли 0 – это валидное значение для курса валют. Так же как и отрицательное значение, например. Это можно провалидировать в конструкторе ExchangeRate с падением. Тогда тут уже на 0 проверять не надо будет

2023-02-23 18:38 UTC, oleg-grigorijan commented on src/by/tms/lesson14/homework/currency/ExchangeService.java
> +                    : (inputCurRate.multiply(exchangeMoney).divide(outputCurRate,2, RoundingMode.HALF_UP));
А если inputCurrency == BYN? 
Можно сделать изящнее. Для базовой валюты создай фиктивный курс new ExchangeRage(BYN, BigDecimal.ONE). Тогда тут не нужно будет сложных условий

2023-02-23 18:41 UTC, oleg-grigorijan commented
Примени автоформатирование

2023-02-23 18:49 UTC, VlaPol commented on src/Homework14Test.java
> +                    Currency outputCurrency = Currency.valueOf(scanner.nextLine());
согласен, пропустил

2023-02-23 18:50 UTC, VlaPol commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +    private BigDecimal rate;
изменил

2023-02-23 19:26 UTC, VlaPol commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +    public ExchangeRate getExchangeRate(Currency currency){
Да, согласен. Я немного недопонял условие. Класс изменил

2023-02-23 19:27 UTC, VlaPol commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +    private static BigDecimal currentRates(Currency currency) {
В соответствии с изменениями ExchangeRate изменил и второй класс

2023-02-23 19:32 UTC, VlaPol commented on src/by/tms/lesson14/homework/currency/ExchangeService.java
> +        BigDecimal outputCurRate = new BigDecimal(0);
Изменил

2023-02-23 19:48 UTC, VlaPol commented on src/by/tms/lesson14/homework/currency/ExchangeService.java
> +                    : (inputCurRate.multiply(exchangeMoney).divide(outputCurRate,2, RoundingMode.HALF_UP));
Да, действительно убралась лишняя проверка. Хороший вариант

2023-02-23 19:48 UTC, VlaPol commented on src/by/tms/lesson14/homework/currency/ExchangeService.java
> +            return outputCurRate.compareTo(BigDecimal.ZERO) == 0
Перенес проверку

2023-02-23 20:34 UTC, oleg-grigorijan requested changes

2023-02-23 20:34 UTC, oleg-grigorijan commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +        if(rate.compareTo(BigDecimal.ZERO) == 0){
Как и писал, отрицательные значения тоже невалидные

2023-02-23 20:34 UTC, oleg-grigorijan commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +        return rate.round(new MathContext(5));
Зачем конкретно в этом месте понадобилось округление?

2023-02-24 03:28 UTC, VlaPol commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +        return rate.round(new MathContext(5));
согласен, нет смысла. ничего не меняется

2023-02-24 03:43 UTC, VlaPol commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +        if(rate.compareTo(BigDecimal.ZERO) == 0){
Проверку добавил. По форматированию: или у меня пробелмы с идеей иил я не знаю, т.к. на каждом классе применил форматирование и проверил изменения. идея показывает что все отформатировано

2023-02-24 05:45 UTC, oleg-grigorijan commented on src/by/tms/lesson14/homework/currency/ExchangeRate.java
> +        if(rate.compareTo(BigDecimal.ZERO) == 0){
Вот теперь отформатировано. Если посмотришь изменения последнего коммита, то увидишь добавленные пробелы вокруг круглых скобок if

2023-02-24 05:45 UTC, oleg-grigorijan approved these changes

2023-02-24 05:50 UTC, merged